/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickbill;

/**
 *
 * @author rizkyandre
 */
public class FormDataKasir extends javax.swing.JPanel {

    /**
     * Creates new form FormDataBarang
     */
    public FormDataKasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNoIdKasir = new javax.swing.JLabel();
        fieldNoIdKasir = new javax.swing.JTextField();
        labelNamaKasir = new javax.swing.JLabel();
        fieldNamaKasir = new javax.swing.JTextField();
        labelKontakKasir = new javax.swing.JLabel();
        fieldKontakKasir = new javax.swing.JTextField();
        labelAlamatKasir = new javax.swing.JLabel();
        fieldAlamatKasir = new javax.swing.JTextField();
        labelEmailKasir = new javax.swing.JLabel();
        fieldEmailKasir = new javax.swing.JTextField();
        labelKataSandiKasir = new javax.swing.JLabel();
        fieldKataSandiKasir = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnTambahKasir = new javax.swing.JButton();

        labelNoIdKasir.setText("No Id Kasir :");

        labelNamaKasir.setText("Nama Kasir :");

        labelKontakKasir.setText("Kontak Kasir :");

        fieldKontakKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKontakKasirActionPerformed(evt);
            }
        });

        labelAlamatKasir.setText("Alamat Kasir :");

        fieldAlamatKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAlamatKasirActionPerformed(evt);
            }
        });

        labelEmailKasir.setText("Email Kasir :");

        fieldEmailKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailKasirActionPerformed(evt);
            }
        });

        labelKataSandiKasir.setText("Kata Sandi Kasir :");

        fieldKataSandiKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKataSandiKasirActionPerformed(evt);
            }
        });

        btnTambahKasir.setText("Tambah Kasir");
        btnTambahKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKasirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(btnTambahKasir))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahKasir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fieldNoIdKasir)
            .addComponent(fieldNamaKasir)
            .addComponent(fieldKontakKasir)
            .addComponent(fieldAlamatKasir)
            .addComponent(fieldEmailKasir)
            .addComponent(fieldKataSandiKasir)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNoIdKasir)
                    .addComponent(labelNamaKasir)
                    .addComponent(labelKontakKasir)
                    .addComponent(labelAlamatKasir)
                    .addComponent(labelEmailKasir)
                    .addComponent(labelKataSandiKasir))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelNoIdKasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNoIdKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNamaKasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelKontakKasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldKontakKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAlamatKasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldAlamatKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEmailKasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldEmailKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelKataSandiKasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldKataSandiKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldKontakKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKontakKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKontakKasirActionPerformed

    private void fieldAlamatKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAlamatKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAlamatKasirActionPerformed

    private void fieldEmailKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailKasirActionPerformed

    private void fieldKataSandiKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKataSandiKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKataSandiKasirActionPerformed

    private void btnTambahKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKasirActionPerformed
        // TODO add your handling code here:
        String noIdKasir = fieldNoIdKasir.getText();
        String namaKasir = fieldNamaKasir.getText();
        String kontakKasir = fieldKontakKasir.getText();
        String alamatKasir = fieldAlamatKasir.getText();
        String emailKasir = fieldEmailKasir.getText();
        String kataSandiKasir = fieldKataSandiKasir.getText();
        
        new DaftarDataKasir().tambahDataKasir(noIdKasir, namaKasir, kontakKasir, alamatKasir, emailKasir, kataSandiKasir);

        fieldNoIdKasir.setText("");
        fieldNamaKasir.setText("");
        fieldKontakKasir.setText("");
        fieldKataSandiKasir.setText("");
        fieldEmailKasir.setText("");
        fieldAlamatKasir.setText("");
    }//GEN-LAST:event_btnTambahKasirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahKasir;
    private javax.swing.JTextField fieldAlamatKasir;
    private javax.swing.JTextField fieldEmailKasir;
    private javax.swing.JTextField fieldKataSandiKasir;
    private javax.swing.JTextField fieldKontakKasir;
    private javax.swing.JTextField fieldNamaKasir;
    private javax.swing.JTextField fieldNoIdKasir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlamatKasir;
    private javax.swing.JLabel labelEmailKasir;
    private javax.swing.JLabel labelKataSandiKasir;
    private javax.swing.JLabel labelKontakKasir;
    private javax.swing.JLabel labelNamaKasir;
    private javax.swing.JLabel labelNoIdKasir;
    // End of variables declaration//GEN-END:variables
}
