/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickbill;

/**
 *
 * @author rizkyandre
 */
public class FormDataBarang extends javax.swing.JPanel {

    /**
     * Creates new form FormDataBarang
     */
    public FormDataBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNoIdBarang = new javax.swing.JLabel();
        fieldNoIdBarang = new javax.swing.JTextField();
        labelNamaBarang = new javax.swing.JLabel();
        fieldNamaBarang = new javax.swing.JTextField();
        labelHargaBarang = new javax.swing.JLabel();
        fieldHargaBarang = new javax.swing.JTextField();
        labelJumlahBarangTersedia = new javax.swing.JLabel();
        fieldJumlahBarangTersedia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnTambahBarang = new javax.swing.JButton();

        labelNoIdBarang.setText("No Id Barang :");

        fieldNoIdBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNoIdBarangActionPerformed(evt);
            }
        });

        labelNamaBarang.setText("Nama Barang :");

        labelHargaBarang.setText("Harga Barang :");

        fieldHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHargaBarangActionPerformed(evt);
            }
        });

        labelJumlahBarangTersedia.setText("Jumlah Barang Tersedia : ");

        fieldJumlahBarangTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJumlahBarangTersediaActionPerformed(evt);
            }
        });

        btnTambahBarang.setText("Tambah Barang");
        btnTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTambahBarang))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahBarang)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNoIdBarang)
                    .addComponent(labelNamaBarang)
                    .addComponent(labelHargaBarang)
                    .addComponent(labelJumlahBarangTersedia))
                .addGap(0, 280, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fieldNoIdBarang)
            .addComponent(fieldNamaBarang)
            .addComponent(fieldHargaBarang)
            .addComponent(fieldJumlahBarangTersedia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelNoIdBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNoIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNamaBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHargaBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelJumlahBarangTersedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldJumlahBarangTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHargaBarangActionPerformed

    private void fieldJumlahBarangTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJumlahBarangTersediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJumlahBarangTersediaActionPerformed

    private void fieldNoIdBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNoIdBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNoIdBarangActionPerformed

    private void btnTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBarangActionPerformed
        // TODO add your handling code here:
        String NoIdBarang;
        String namaBarang;
        int hargaBarang;
        int jumlahBarangTersedia;
        
        NoIdBarang = fieldNoIdBarang.getText();
        namaBarang = fieldNamaBarang.getText();
        hargaBarang = Integer.parseInt(fieldHargaBarang.getText());
        jumlahBarangTersedia = Integer.parseInt(fieldJumlahBarangTersedia.getText());
//        System.out.printf("Form data barang : %s %s %d %d", NoIdBarang, namaBarang, hargaBarang, jumlahBarangTersedia);
        
        new DaftarDataBarang().tambahDataBarang(NoIdBarang, namaBarang, hargaBarang, jumlahBarangTersedia);
        fieldNoIdBarang.setText("");
        fieldNamaBarang.setText("");
        fieldHargaBarang.setText("");
        fieldJumlahBarangTersedia.setText("");
    }//GEN-LAST:event_btnTambahBarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahBarang;
    private javax.swing.JTextField fieldHargaBarang;
    private javax.swing.JTextField fieldJumlahBarangTersedia;
    private javax.swing.JTextField fieldNamaBarang;
    private javax.swing.JTextField fieldNoIdBarang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHargaBarang;
    private javax.swing.JLabel labelJumlahBarangTersedia;
    private javax.swing.JLabel labelNamaBarang;
    private javax.swing.JLabel labelNoIdBarang;
    // End of variables declaration//GEN-END:variables
}
