/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickbill;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rzkan
 */
public class WindowDataKasir extends javax.swing.JFrame {

    /**
     * Creates new form WindowDataBarang
     * @param kasir
     */
    public WindowDataKasir(ResultSet kasir) {
        initComponents();        
        String noIdKasir;
        String namaKasir;
        String kontakKasir;
        String alamatKasir;
        String emailKasir;
        String kataSandiKasir;
        
        try {
            while (kasir.next()) {
                noIdKasir = kasir.getString(1);
                namaKasir = kasir.getString(2);
                kontakKasir = kasir.getString(3);
                alamatKasir = kasir.getString(4);
                emailKasir = kasir.getString(5);
                
                textNoIdKasir.setText(noIdKasir);
                textNamaKasir.setText(namaKasir);
                textKontakKasir.setText(kontakKasir);
                textAlamatKasir.setText(alamatKasir);
                textEmailKasir.setText(emailKasir);
            }
        } catch (SQLException ex) {
            Logger.getLogger(WindowDataKasir.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }

    private WindowDataKasir() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleDataKasir = new javax.swing.JLabel();
        titleNoIdKasir = new javax.swing.JLabel();
        textNoIdKasir = new javax.swing.JLabel();
        titleNamaKasir = new javax.swing.JLabel();
        textNamaKasir = new javax.swing.JLabel();
        titleKontakKasir = new javax.swing.JLabel();
        textKontakKasir = new javax.swing.JLabel();
        titleAlamatKasir = new javax.swing.JLabel();
        textAlamatKasir = new javax.swing.JLabel();
        titleEmailKasir = new javax.swing.JLabel();
        textEmailKasir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Kasir");

        titleDataKasir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleDataKasir.setText("Data Kasir");

        titleNoIdKasir.setText("No Id Kasir                   :");

        textNoIdKasir.setText("jLabel6");

        titleNamaKasir.setText("Nama Kasir                   :");

        textNamaKasir.setText("jLabel6");

        titleKontakKasir.setText("Kontak Kasir                 :");

        textKontakKasir.setText("jLabel6");

        titleAlamatKasir.setText("Alamat Kasir                 :");

        textAlamatKasir.setText("jLabel6");

        titleEmailKasir.setText("Email Kasir                   :");

        textEmailKasir.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleDataKasir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleEmailKasir)
                        .addGap(20, 20, 20)
                        .addComponent(textEmailKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(titleKontakKasir)
                                .addGap(18, 18, 18)
                                .addComponent(textKontakKasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(titleNamaKasir)
                                .addGap(18, 18, 18)
                                .addComponent(textNamaKasir))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(titleNoIdKasir)
                                .addGap(18, 18, 18)
                                .addComponent(textNoIdKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleAlamatKasir)
                        .addGap(20, 20, 20)
                        .addComponent(textAlamatKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(74, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleDataKasir)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNoIdKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNoIdKasir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNamaKasir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKontakKasir)
                    .addComponent(titleKontakKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleAlamatKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAlamatKasir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEmailKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmailKasir))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowDataKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowDataKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowDataKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowDataKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowDataKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel textAlamatKasir;
    private javax.swing.JLabel textEmailKasir;
    private javax.swing.JLabel textKontakKasir;
    private javax.swing.JLabel textNamaKasir;
    private javax.swing.JLabel textNoIdKasir;
    private javax.swing.JLabel titleAlamatKasir;
    private javax.swing.JLabel titleDataKasir;
    private javax.swing.JLabel titleEmailKasir;
    private javax.swing.JLabel titleKontakKasir;
    private javax.swing.JLabel titleNamaKasir;
    private javax.swing.JLabel titleNoIdKasir;
    // End of variables declaration//GEN-END:variables
}
